name: HTML-Widget
version: 1.0
abstract: HTML Widget And Validation Framework
author: Sebastian Riedel, C<sri@oook.de>
license: perl
distribution_type: module
requires:
  perl: 5.8.1
  HTML::Element: 0
  Class::Accessor::Fast: 0
  Class::Accessor::Chained::Fast: 0
  Email::Valid: 0
  Date::Calc: 0
  Test::MockObject: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.45
